# Generated by Django 4.2.7 on 2023-11-26 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('users', '0002_user_is_admin_user_is_super_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='area_users', to='companies.area'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_users', to='companies.company'),
        ),
    ]
