# Generated by Django 4.2.1 on 2023-11-10 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reset_password', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetpassworddata',
            name='has_been_used',
            field=models.BooleanField(default=False),
        ),
    ]
