# Generated by Django 4.2.7 on 2023-11-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_file_area_alter_file_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date',
        ),
        migrations.AddField(
            model_name='file',
            name='month',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='file',
            name='year',
            field=models.IntegerField(default=2023),
        ),
    ]
