# Generated by Django 4.2.7 on 2023-11-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_remove_file_date_file_month_file_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='file',
            name='year',
            field=models.IntegerField(),
        ),
    ]
