# Generated by Django 4.2.7 on 2023-11-26 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('files', '0004_alter_file_month_alter_file_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('company', 'area', 'year', 'month')},
        ),
        migrations.AlterModelTable(
            name='file',
            table='files',
        ),
    ]
