# Generated by Django 4.2.7 on 2023-11-26 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_alter_file_loaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='file',
            name='year',
            field=models.IntegerField(verbose_name=(django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100))),
        ),
    ]
