# Generated by Django 4.2.7 on 2023-11-26 22:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_alter_file_month_alter_file_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
