# Generated by Django 4.2.7 on 2023-12-05 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_alter_file_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='file',
            options={'ordering': ('-year', '-month')},
        ),
    ]
