# Generated by Django 4.2.7 on 2023-12-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_alter_file_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uploaded_filename',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
