# Generated by Django 4.2.7 on 2023-12-10 22:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0011_materfiletypes_alter_file_file_masterfiles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MasterFiles',
            new_name='MasterFile',
        ),
        migrations.RenameModel(
            old_name='MaterFileTypes',
            new_name='MasterFileType',
        ),
    ]
