# Generated by Django 4.2.7 on 2023-12-13 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_rename_masterfiles_masterfile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='last_version',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_level', models.CharField(max_length=20, null=True)),
                ('is_transactional', models.BooleanField()),
                ('account_number', models.CharField(max_length=20)),
                ('account_name', models.CharField(max_length=100)),
                ('third_code', models.CharField(max_length=20, null=True)),
                ('branch', models.CharField(max_length=20, null=True)),
                ('third_name', models.CharField(max_length=100, null=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('debit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=15)),
                ('final_balance', models.DecimalField(decimal_places=2, max_digits=15)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reprocessing', models.BooleanField(default=True)),
                ('version', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='files.file')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
    ]
