# Generated by Django 4.2.7 on 2023-12-13 22:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0013_file_last_version_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='File',
            new_name='TransactionFile',
        ),
        migrations.AlterModelTable(
            name='transactionfile',
            table='transaction_files',
        ),
    ]
