# Generated by Django 4.2.7 on 2023-12-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_rename_value_transactioncolumnnameoption_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncolumnnameoption',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
    ]
