# Generated by Django 4.2.7 on 2023-12-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0018_remove_transaction_is_reprocessing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='index_in_file',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
