# Generated by Django 4.2.7 on 2023-12-26 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('files', '0020_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='transactionfile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_adjustment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionfile',
            name='is_adjustment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='version',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='transactionfile',
            name='last_version',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='transactionfile',
            unique_together={('company', 'area', 'year', 'month', 'is_adjustment')},
        ),
    ]
