# Generated by Django 4.2.7 on 2024-01-17 17:05

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0021_alter_transactionfile_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterfile',
            name='file',
            field=models.FileField(upload_to=files.models.MasterFile.get_company_directory_path),
        ),
        migrations.AlterField(
            model_name='transactionfile',
            name='file',
            field=models.FileField(upload_to=files.models.TransactionFile.get_company_directory_path),
        ),
    ]
