# Generated by Django 4.2.7 on 2024-01-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
        ('files', '0022_alter_masterfile_file_alter_transactionfile_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='masterfile',
            unique_together={('company', 'area', 'type')},
        ),
    ]
